### ISSUE TITLE
Why using static functions and not real object ?

### ISSUE THREAD

**Issue by jerrywham** [SRWieZ/thumbhash#2]
When you use static functions, it is like you use global procedural functions outside an object.
Read what Tom Butler said about this : https://r.je/static-methods-bad-practice

**Comment by marconett** [comment]
* it's a direct translation of the js version of thumbhash, which was written in a functional manner
* the way it is written, every function is self-contained and there is no internal state to keep track of
* it's a class so that it's psr-4 compatible without defining global functions

**Comment by SRWieZ** [comment]
Interesting article. 

@marconett answered your question better than I would. 🙂
