### ISSUE TITLE
Recommendations for optimising encoding performance

### ISSUE THREAD

**Issue by binaryfire** [SRWieZ/thumbhash#5]
Thanks for creating this package. My multi tenant app has a media library feature and I’d like to  generate a thumbhash for each uploaded image.

I’m already generating multiple sizes using php-vips so I don’t want to add much more overhead.

With Blurhash, I first generate a tiny (32px) image with vips and use that for hashing. Would that be the best approach here too?

**Comment by SRWieZ** [comment]
Yes, you should do it in this order.
